"""quotation update2

Revision ID: 0d1ef25adbeb
Revises: e80c0399184b
Create Date: 2024-03-20 05:19:22.381140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d1ef25adbeb'
down_revision: Union[str, None] = 'e80c0399184b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_product',
    sa.Column('quotation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='quotation_product_ibfk_1'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name='quotation_product_ibfk_2'),
    sa.PrimaryKeyConstraint('quotation_id', 'product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
