"""user attribute nullable

Revision ID: 302e0e36db36
Revises: 3f455f8f535c
Create Date: 2024-06-25 20:09:40.725350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '302e0e36db36'
down_revision: Union[str, None] = '3f455f8f535c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_product')
    op.alter_column('users', 'social',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'client_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
