"""FAQ init

Revision ID: 35d737652d42
Revises: 61275459cf4d
Create Date: 2024-08-16 02:33:06.894140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35d737652d42'
down_revision: Union[str, None] = '61275459cf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_product')
    op.drop_index('ix_custom_products_category', table_name='custom_products')
    op.drop_index('ix_custom_products_id', table_name='custom_products')
    op.drop_index('ix_custom_products_name', table_name='custom_products')
    op.drop_table('custom_products')
    op.drop_index('ix_notices_id', table_name='notices')
    op.drop_index('ix_notices_title', table_name='notices')
    op.drop_table('notices')
    op.drop_index('ix_past_orders_client_id', table_name='past_orders')
    op.drop_index('ix_past_orders_id', table_name='past_orders')
    op.drop_index('ix_past_orders_name', table_name='past_orders')
    op.drop_table('past_orders')
    # ### end Alembic commands ###


def upgrade() -> None:
    op.create_table(
        'faqs',
        sa.Column('id', sa.Integer(), autoincrement=True, primary_key=True, index=True),
        sa.Column('category', sa.String(length=30), nullable=False, index=True),
        sa.Column('question', sa.String(length=255), nullable=False, index=True),
        sa.Column('answer', sa.TEXT, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.current_timestamp()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    )

def downgrade() -> None:
    op.drop_table('faqs')
