"""quotation add attribute input_date

Revision ID: 4e72c9e0a4da
Revises: 35d737652d42
Create Date: 2024-09-14 13:11:56.251893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e72c9e0a4da'
down_revision: Union[str, None] = '35d737652d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('input_date', sa.Date))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
