"""quotation_product_back

Revision ID: 87c3fb06dbec
Revises: 1ab3f1aa2caa
Create Date: 2024-03-21 16:49:33.339280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = '87c3fb06dbec'
down_revision: Union[str, None] = '1ab3f1aa2caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'quotation_product',
        sa.Column('quotation_id', sa.Integer(), sa.ForeignKey('quotations.id'), primary_key=True),
        sa.Column('product_id', sa.Integer(), sa.ForeignKey('products.id'), primary_key=True),
        sa.Column('price', sa.Integer()),
        sa.Column('quantity', sa.Integer()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=func.now())
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
