"""product_date_update

Revision ID: 9e337d0b1ae9
Revises: 6ac556ada880
Create Date: 2024-03-20 02:19:30.533916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '9e337d0b1ae9'
down_revision: Union[str, None] = '6ac556ada880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=func.now()))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, server_default=func.now(), onupdate=func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
