"""past_orders init

Revision ID: d17fca85a59b
Revises: 4c4731b47610
Create Date: 2024-06-28 21:36:48.735918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd17fca85a59b'
down_revision: Union[str, None] = '4c4731b47610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('product_ids', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_past_orders_client_id'), 'past_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_past_orders_id'), 'past_orders', ['id'], unique=False)
    op.create_index(op.f('ix_past_orders_name'), 'past_orders', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_past_orders_name'), table_name='past_orders')
    op.drop_index(op.f('ix_past_orders_id'), table_name='past_orders')
    op.drop_index(op.f('ix_past_orders_client_id'), table_name='past_orders')
    op.drop_table('past_orders')
    # ### end Alembic commands ###
