"""quotation_product

Revision ID: e756f75af337
Revises: 3e07f3420165
Create Date: 2024-03-21 11:18:02.321174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = 'e756f75af337'
down_revision: Union[str, None] = '3e07f3420165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'quotation_product',
        sa.Column('quotation_id', sa.Integer(), sa.ForeignKey('quotations.id'), primary_key=True),
        sa.Column('product_id', sa.Integer(), sa.ForeignKey('products.id'), primary_key=True),
        sa.Column('price', sa.Integer()),
        sa.Column('number', sa.Integer()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
