"""quotation update

Revision ID: e80c0399184b
Revises: 6b5726a4f404
Create Date: 2024-03-20 05:15:13.783046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80c0399184b'
down_revision: Union[str, None] = '6b5726a4f404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_product', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('quotation_product', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('quotations', sa.Column('total_price', sa.Integer(), nullable=False))
    op.add_column('quotations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('quotations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'updated_at')
    op.drop_column('quotations', 'created_at')
    op.drop_column('quotations', 'total_price')
    op.drop_column('quotation_product', 'number')
    op.drop_column('quotation_product', 'price')
    # ### end Alembic commands ###
