name: Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install pipx
        run: |
          pip install --upgrade pip
          pip install pipx
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry with pipx
        run: |
          pipx install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Update poetry lock file
        run: poetry lock --no-update

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest tests
        continue-on-error: true

      - name: Set up GCP SSH key and known hosts
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          echo "${{ secrets.GCP_HOST_SERVER }} $(ssh-keyscan ${{ secrets.GCP_HOST_SERVER }} 2>/dev/null)" >> ~/.ssh/known_hosts

      - name: Deploy to GCP
        env:
          GCP_HOST_SERVER: ${{ secrets.GCP_HOST_SERVER }}
          GCP_HOST_NAME: ${{ secrets.GCP_HOST_NAME }}
        run: |
          # 먼저 디렉토리 생성
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_HOST_NAME }}@${{ secrets.GCP_HOST_SERVER }} "mkdir -p /home/${{ secrets.GCP_HOST_NAME }}/app"

          # 파일 복사
          scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.GCP_HOST_NAME }}@${{ secrets.GCP_HOST_SERVER }}:/home/${{ secrets.GCP_HOST_NAME }}/app/

          # 나머지 배포 과정
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_HOST_NAME }}@${{ secrets.GCP_HOST_SERVER }} << 'EOF'
            cd /home/${{ secrets.GCP_HOST_NAME }}/app

            # 환경 변수 설정
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            chmod 600 .env

            # 의존성 설치
            poetry config virtualenvs.create true
            poetry install --no-interaction --sync

        
          EOF
